//! The one way rows leave the audit stores (M7 / `QUOTA-001`).
//!
//! [ADR-0005](../../../../docs/adr/0005-SAFETY_EVENTS.md) accepted that
//! `safety_events` grows monotonically and named the consequence: it "needs a
//! retention story that is an explicit, authorized operation rather than a
//! background cleanup." `memory_access_log` is the same store with the same
//! property, and the same argument applies to it.
//!
//! The argument is worth restating, because "just add a retention sweep" is
//! the obvious thing to do and it is wrong here. Every other store this
//! runtime bounds is a by-product: a trace can be regenerated by reading the
//! transcript, an attachment was consumed by the turn that received it, a
//! settled ingress row has already done its job. These two are the record of
//! who was allowed to do what. A timer that deleted from them would mean the
//! answer to "was this approved" silently becomes "there is no row" after
//! ninety days — which is the exact failure mode the ADR's "deletion is never
//! the record of an outcome" exists to prevent, arrived at from the other
//! direction.
//!
//! So deletion here is a thing a person does, on purpose, having been shown
//! what it would remove. [`purge_before`] rechecks that report inside the
//! deletion transaction and writes the `audit_purged` marker in that same
//! transaction. A changed count or failed marker leaves every row intact.

use super::event::{SafetyEvent, SafetyEventKind, SafetyOutcome};
use super::journal::SafetyLogError;
use crate::memory::SqliteStore;
use rusqlite::params;
use std::sync::Arc;

/// How many rows each store holds before and after — or would lose, when
/// nothing has been applied yet.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct AuditPurgeCounts {
    pub safety_events: usize,
    pub memory_access_log: usize,
}

impl AuditPurgeCounts {
    pub fn total(&self) -> usize {
        self.safety_events + self.memory_access_log
    }

    pub fn is_empty(&self) -> bool {
        self.total() == 0
    }
}

/// Count what a purge at `before_unix` would remove, without removing it.
///
/// The report an operator has to read before they can apply one. Both stores
/// are counted in a single call because they are purged together: a deployment
/// that kept one and not the other would have a memory-access history that
/// outlives the record of what was authorized, which answers no question well.
pub fn count_before(
    store: &SqliteStore,
    before_unix: u64,
) -> Result<AuditPurgeCounts, SafetyLogError> {
    let conn = store
        .audit_conn()
        .map_err(|err| SafetyLogError::Backend(Arc::from(err.to_string())))?;
    // The cutoff is rendered by SQLite rather than formatted here: both
    // columns are written by `CURRENT_TIMESTAMP`, and an RFC 3339 literal
    // would compare wrong against `YYYY-MM-DD HH:MM:SS` on the `T` alone.
    let count = |sql: &str| -> Result<usize, SafetyLogError> {
        conn.query_row(sql, params![before_unix as i64], |row| row.get::<_, i64>(0))
            .map_err(sqlite_error)
            .map(|count| count.max(0) as usize)
    };
    let counts = AuditPurgeCounts {
        safety_events: count(
            "SELECT COUNT(*) FROM safety_events WHERE recorded_at < datetime(?1, 'unixepoch')",
        )?,
        memory_access_log: count(
            "SELECT COUNT(*) FROM memory_access_log WHERE created_at < datetime(?1, 'unixepoch')",
        )?,
    };
    Ok(counts)
}

/// Delete rows older than `before_unix` from both audit stores and record that
/// it happened in one transaction.
///
/// `operator` is whatever identifies the person doing this — it lands in the
/// event's subject, unredacted, because an audit purge with no attribution is
/// the deletion this whole module exists to make impossible.
///
/// `expected` is the report the operator confirmed. It is re-counted after the
/// transaction begins, before deletion. The event insert follows the deletes
/// in that transaction, after the cutoff deletes have already run; any insert
/// failure rolls every deletion back.
pub fn purge_before(
    store: &SqliteStore,
    before_unix: u64,
    expected: AuditPurgeCounts,
    operator: &str,
) -> Result<AuditPurgeCounts, SafetyLogError> {
    let mut conn = store
        .audit_conn()
        .map_err(|err| SafetyLogError::Backend(Arc::from(err.to_string())))?;
    let transaction = conn.transaction().map_err(sqlite_error)?;
    let count = |sql: &str| -> Result<usize, SafetyLogError> {
        transaction
            .query_row(sql, params![before_unix as i64], |row| row.get::<_, i64>(0))
            .map_err(sqlite_error)
            .map(|count| count.max(0) as usize)
    };
    let actual = AuditPurgeCounts {
        safety_events: count(
            "SELECT COUNT(*) FROM safety_events WHERE recorded_at < datetime(?1, 'unixepoch')",
        )?,
        memory_access_log: count(
            "SELECT COUNT(*) FROM memory_access_log WHERE created_at < datetime(?1, 'unixepoch')",
        )?,
    };
    if actual != expected {
        return Err(SafetyLogError::Backend(Arc::from(format!(
            "audit purge confirmation is stale: expected {} safety event(s) and {} memory access row(s), found {} and {}",
            expected.safety_events,
            expected.memory_access_log,
            actual.safety_events,
            actual.memory_access_log
        ))));
    }
    let safety_events = transaction
        .execute(
            "DELETE FROM safety_events WHERE recorded_at < datetime(?1, 'unixepoch')",
            params![before_unix as i64],
        )
        .map_err(sqlite_error)?;
    let memory_access_log = transaction
        .execute(
            "DELETE FROM memory_access_log WHERE created_at < datetime(?1, 'unixepoch')",
            params![before_unix as i64],
        )
        .map_err(sqlite_error)?;
    let counts = AuditPurgeCounts {
        safety_events,
        memory_access_log,
    };
    super::sqlite::insert_event(
        &transaction,
        &SafetyEvent::new(
            SafetyEventKind::AuditPurged,
            SafetyOutcome::Purged,
            format!("audit stores purged by {operator}"),
        )
        .with_detail(format!(
            "{} safety events and {} memory access rows recorded before {before_unix} deleted",
            counts.safety_events, counts.memory_access_log
        )),
    )?;
    transaction.commit().map_err(sqlite_error)?;
    Ok(counts)
}

fn sqlite_error(err: rusqlite::Error) -> SafetyLogError {
    SafetyLogError::Backend(Arc::from(err.to_string()))
}
